//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Text.RegularExpressions;



	public class VectorUtils{


		public static Vector3 rotate(Vector3 v, float angle) {
			Vector3 res = new Vector3();
			res.x = v.x * Mathf.Cos(angle) - v.y*Mathf.Sin(angle);
			res.y = v.y * Mathf.Cos(angle) + v.x*Mathf.Sin(angle);
			return (res);

		}



		public static float getAngle(Vector3 v1 , Vector3  v2 ) {
			float l1  = v1.magnitude;
			float l2  = v2.magnitude;
			float cos  = (v1.x * v2.x + v1.y * v2.y) / (l1 * l2);
			float angle = Mathf.Acos(cos);
		    if (v1.x * v2.y < v1.y * v2.x) {
				angle = Mathf.PI * 2 - angle ;
				//angle = - angle;
			}/*

			if (Math.Abs(angle) > Math.PI) {
				if (angle > 0)  { 
					angle =  (float)(Math.PI - angle);
			    } else {
				    angle = (float)( -angle -  Math.PI);
				}
			}*/

			return (float)(-angle/Math.PI *180);
		}

	}


